<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.6">
  <POU Name="MAIN" Id="{8712e83b-f585-4a61-82b9-804ce9b43d9b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	testMethods		: FB_Methods;
	testGenerics	: FB_Generics<100>;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[testMethods.MethodDefaultValue(1);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>